### PR TITLE
Astropy upgrade

### PR DESCRIPTION
**Pull request by wkerzendorf**

### CODE REVIEW

**Comment by wkerzendorf** [comment]
@followthesheep - can we merge this?

**Comment by followthesheep** [comment]
You removed starkit dependency from starkit? :-)

**Comment by wkerzendorf** [comment]
finally  ;-) it got in the way

**Comment by followthesheep** [comment]
Is this Spectrum1D change supposed to be only for starkit, or do we need to use it as well for passing in Spectrum1D objects into starkit? The original Spectrum1D had a lot of member functions like 'from_array' and 'interpolate'. Is it going to be confusing to have two classes named Spectrum1D? Maybe we can port in the old version of Spectrum1D that works and call it something else?

**Pull request merged**
